# Generated by Django 5.0.6 on 2024-07-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamados',
            old_name='situação',
            new_name='situacao',
        ),
        migrations.RemoveField(
            model_name='dados',
            name='pronome',
        ),
        migrations.AddField(
            model_name='chamados',
            name='assunto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chamados',
            name='texto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
