# Generated by Django 5.0.6 on 2024-07-06 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chamados',
            name='situação',
        ),
        migrations.RemoveField(
            model_name='dados',
            name='pronome',
        ),
        migrations.AddField(
            model_name='chamados',
            name='assunto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chamados',
            name='situacao',
            field=models.CharField(default='Chamado Aberto', max_length=255),
        ),
        migrations.AddField(
            model_name='chamados',
            name='texto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('codigo', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('situacao', models.CharField(blank=True, max_length=255, null=True)),
                ('resposta', models.CharField(blank=True, max_length=255, null=True)),
                ('arquivos', models.ManyToManyField(blank=True, related_name='timelines', to='main.arquivo')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
