# Generated by Django 5.0.6 on 2024-07-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_situação_chamados_situacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='resposta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
